### ISSUE TITLE
vertxbus.js onmessage should accept false.

### ISSUE THREAD

**Issue by FCsean** [vert-x3/vertx-bus-bower#1]
Within sockJSConn.onmessage, there is a conditional that is 
if (body) { 
  handler(body, replyHandler);
}
it should be changed to this so that it can accept false replies or messages. Or however you change it just that it should accept false.
if (body !== undefined && body !== null) {
  handler(body, replyHandler);
}

**Comment by cescoffier** [comment]
The issue should be opened on Vertx-web. This project is just retrieving the verxbus.js from there.

I've opened https://github.com/vert-x3/vertx-web/issues/160. Please follow this one.
