### ISSUE TITLE
Questions about 3.5.0

### ISSUE THREAD

**Issue by leolux** [vert-x3/vertx-bus-bower#11]
There seems to be a lot of changes in 3.5.0 when showing the diff https://github.com/vert-x3/vertx-bus-bower/commit/32065d55128b5861524573d40a0e37a2962087df

1 .Are they affecting the API of the client side using vertx-eventbus.js?
2. Where is a changelog to 3.5.0?

**Comment by vietj** [comment]
I can only comment about 2: https://github.com/vert-x3/wiki/wiki/3.5.0-Release-Notes

**Comment by vietj** [comment]
setting "invalid" as it's a question and not an effective bug/feature

**Comment by leolux** [comment]
When reading the release notes of 3.5.0 there is no word about breaking changes. Can someone confirm that there is no change in the API of vertx-eventbus.js?

There are also changelogs here [1] but they are incomplete.
[1] https://github.com/vert-x3/vertx-bus-bower#changelog

**Comment by pmlopes** [comment]
There are no breaking changes. The changes you see are an optional reconnect feature which was missed from the notes you’re right.
