### ISSUE TITLE
Update bower.json main for 3.1

### ISSUE THREAD

**Issue by earmenda** [vert-x3/vertx-bus-bower#3]
Hi, should the bower.json now have the new file name for the main property?

**Comment by cescoffier** [comment]
Definitely a bug. Is this entry used ?

**Comment by cescoffier** [comment]
Fix in 488dc998fcbd1a5834a1649d698dcb85dcf7cdb0

**Comment by earmenda** [comment]
It can be used by grunt-bower to add dependencies to html. Thanks!

**Comment by cescoffier** [comment]
I'm going to push a 3.1.1 tag so the Bower repository is going to be updated.

**Comment by cescoffier** [comment]
Tag made, bower should be updated shortly.
