### ISSUE TITLE
Something forgotten.

### ISSUE THREAD

**Issue by elopezvalecky** [vert-x3/vertx-bus-bower#4]
Hi,
I think there is something forgotten after the migration to the version 3, take a look the line 278 on the javascript.

``` javascript
  EventBus.prototype.close = function () {
    this.state = vertx.EventBus.CLOSING;  // <------------------------------------
    this.sockJSConn.close();
  };
```

that line should be **this.state = EventBus.CLOSING**, without the prefix _vertx._, right?

**Comment by pmlopes** [comment]
right!

**Comment by pmlopes** [comment]
the code lives on vert.x-web so will close this issue and track it there
