### ISSUE TITLE
close is not defined

### ISSUE THREAD

**Issue by a-marcel** [vert-x3/vertx-bus-bower#5]
Hello,

can someone fix this Line in the bower and NPM Package ?

```
/**
 * Closes the connection to the EvenBus Bridge.
 */
EventBus.prototype.close = function () {
  this.state = vertx.EventBus.CLOSING;
  this.sockJSConn.close();
};
```

vertx is not defined -> should be:

```
this.state = EventBus.CLOSING;
```

Thanks

**Comment by cescoffier** [comment]
This issue should be opened on vertx-web that provides the bridge.
I've opened https://github.com/vert-x3/vertx-web/issues/260.

**Comment by pmlopes** [comment]
duplicate of #4
