### ISSUE TITLE
eventBus.send() does not go to the server after second browser connects

### ISSUE THREAD

**Issue by nielsbaloe** [vert-x3/vertx-bus-bower#7]
Hi,

I'm having great difficulties with the eventbus. I found out that an eventBus.send() always goes to the last-connected browser, but NOT to the server! Help. I really need to be able to communicate with the server, no matter how many other browsers have connected or how what messages were sent before.

Server code:
https://github.com/nielsbaloe/vertx-ui/blob/master/master/src/main/java/live/connector/vertxui/server/samples/chatEventBus/ExampleChatEventbus.java

Client code:
https://github.com/nielsbaloe/vertx-ui/blob/master/master/src/main/java/live/connector/vertxui/client/samples/chatEventBus/Client.java

You can download the project, run ExampleChatEventBus and open a browser twice pointed at http://localhost (enter a name twice). You will see "I want a reply" appearing in the browser instead of the server.

Much thanks fixing, I'm building a whole java+javascript ecosystem around the eventbus but this isn't helping. Thanks!
Niels

**Comment by alexlehm** [comment]
(edit: answered the questions on the group thread instead, its better to clarify the questions there https://groups.google.com/d/msg/vertx/0shVePhqs_Y/R_9SM8_TFQAJ)

the event bus is a bus meaning that all connected clients are treated the same, when using send (i.e. point to point messaging). The connection between the sending client and the receiving client (which is chosen by round robin) can be replies multiple times, but you have to control over which client receives the message. To implement a chat pm type communication, I think you have to create a eb address for each client that is used by this client exclusively like e.g. chat.Username

http://vertx.io/docs/vertx-core/js/#_point_to_point_and_request_response_messaging

**Comment by nielsbaloe** [comment]
I don't think you understand me. The chat is working fine. I already have it running, with just a few lines of code, using eventBus.publish(). I now have three beautiful small implementations: with websockets, sockJS and eventBus. They all work perfectly!

Your reply sounds as if I'm talking about send() on the serverside. That is not true. I mean send() on the clientside. I need consistent behaviour there. Or, I want to say something to the server alone. How can I say something to the client? And why does send() means something different?

Super thanks!

**Comment by alexlehm** [comment]
There is no distinction between client and server, all are connected to the event bus, so a client will talk to a random peer (either a client or the server) when using send, the message will reach one peer and that one will be responsible for doing the operation with it.

**Comment by alexlehm** [comment]
btw, could we please continue the discussion on the google group post, as this is probably picked by more people this way?

**Comment by nielsbaloe** [comment]
OK, now I understand, thanks!

Suppose I make a seperate eventBus just for client-server communication only. That would always fail, because when multiple browsers connect to the same page, the send() call will get unpredictable. I think I'll just use sockJS because the send() there is always to the one that was connected to in the first place.
Thanks again!!
PS. I mailed to the google groups days ago, but no one replied. Sorry for posting here!

**Comment by alexlehm** [comment]
(I answered the group post after I answered here, sorry)
