### ISSUE TITLE
Messages are anonymous: there is no sender or other identification in a message

### ISSUE THREAD

**Issue by nielsbaloe** [vert-x3/vertx-bus-bower#8]
Hi,

At the serverside, I have another big problem. There is no way to tell who has sended the message. Using pure websockets or sockjs at least I have the socket .writeHandlerID()/textHandlerID(), but using the eventbus there is no way to tell who's sending.

The message.replyAddress() is something special for that send/receive only, so that isn't helping.
I suggest to introduce a message.senderID() which matches the writeHandlerID/textHandlerID.

Thanks for any help! Without any help, it's not really possible to use the vertx-eventbus in a usefull way I'm afraid...

Niels

**Comment by alexlehm** [comment]
Couldn't you put a transaction id of some kind into your message?

**Comment by nielsbaloe** [comment]
That would be very unsafe if it is done clientside. It would mean that I can login as John and then tell the server that I'm Frank. 

As workaround I'm doing something similar serverside: I insert the socket().writeHandlerID() into the message-header, but, this is really a workaround, I can't image that the vertx-eventbus is of any use for anyone without knowing who sended it ;)

**Comment by alexlehm** [comment]
You will have to do some kind of authentication or session anyway when you want to have a secured access, which the event bus doesn't do by default.
The event bus does not follow the use case you want, it enables communication between all peers, anything else has to be implemented on top of that.

**Comment by nielsbaloe** [comment]
OK, I understand, thanks. However, my guess is that it's usefull to know who sended it anyway, so my request to include a message.sender() still stands.

**Comment by cescoffier** [comment]
Message orientation promotes loose coupling. You don't necessary wants to know who send the message and who process it. 

To do what you want, use some kind of authentication and HTTPs (WSS). Once you are logged in, you would get some kind of token that you can add to your message. Notice that it's the approach used by most APIs where you pass an access token.
