### ISSUE TITLE
SockJS version and CDN and documentation

### ISSUE THREAD

**Issue by nielsbaloe** [vert-x3/vertx-bus-bower#9]
Hi,

Some minor issues:

- reading the sourcecode I could find out how to use the vertx-eventbus.js . Please provide documentation which a description of all input- and output parameters for all methods. Or: I couldn't find it, where is it?

- The Vert.X docs for vertx-eventbus still use sockJS 0.3.4 at http://vertx.io/docs/vertx-web/java/#_sockjs . Maybe you want to update and verify whether it's all good and sound with the current SockJS 1.1.1 . 

- Why is the vertx-eventbus.js not available through any CDN? Not yet taken care of perhaps? I don't want to serve it myself from my own server to browsers - just like I don't provide jquery libraries and such. So where is the CDN? Can I help providing it?

Thanks,
Niels

**Comment by alexlehm** [comment]
the documentation is in the jsdoc here http://vertx.io/docs/jsdoc/module-vertx-js_event_bus-EventBus.html

(cant say anything for the other two questions)

**Comment by nielsbaloe** [comment]
Thanks!

**Comment by cescoffier** [comment]
About sockJS, the latest version is not 1.1.1. 1.1.1 is sockjs-client, not sockjs. The latest version of sockJS is 0.3.18 (https://www.npmjs.com/package/sockjs). Yes, we are behind, but not much.

**Comment by cescoffier** [comment]
About CDN, no, we never did the process to upload the eventbus client to a CDN. I don't even know the process. It would be possible I think. Do you know the process ?

**Comment by nielsbaloe** [comment]
Thanks for all your answers, I understand now the eventBus should stay anonymous. 

That NPMJS link you gave, actually I should add my package there too, as a Java2Javascript bridge access. Or, it might be usefull as a link here, as it's a mapper to your vertx-bower project instead of code doing anything.

I guess getting vertx-eventbus on a CDN is a matter of submitting it. I'll invest some time in figuring that out.

**Comment by alexlehm** [comment]
I know of two cdn services which are free for opensource (there may be more), cdnjs.com and jsdeliver.com.

cdnjs.com is backed by Cloudflare, jsdeliver is backed by more than one service.

Both have a moderated pull request system for including or updating libraries I think

**Comment by nielsbaloe** [comment]
Yes, those are the ones I had in mind. I already did a request at cdnjs.com a while ago, probably not properly formatted, so that request was dismissed. Both CDNs work by a pull request:

- https://github.com/cdnjs/cdnjs at "Adding a new or updating an existing library"
- https://github.com/jsdelivr/jsdelivr/blob/master/CONTRIBUTING.md

Can I be of any assistence?

**Comment by cescoffier** [comment]
@pmlopes @vietj  what do you think? It looks straightforward to add this to our release process. However, I believe that one CDN would be enough no ?

**Comment by pmlopes** [comment]
Just to clarify the client version 1.1.1 is independent of the server, the server must implement a spec version, currently the latest spec version is 0.3.3 as per this repo: https://github.com/sockjs/sockjs-protocol and that is the version we implement: https://github.com/vert-x3/vertx-web/blob/master/vertx-web/src/main/java/io/vertx/ext/web/handler/sockjs/SockJSHandler.java#L31

**Comment by pmlopes** [comment]
This is being addressed by CDNJS here: https://github.com/cdnjs/cdnjs/pull/10416
